services:
  - type: web
    name: university-exam-surveillance
    env: node
    buildCommand: npm install --force && npm run build
    startCommand: npm start
    envVars:
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: JWT_SECRET
        sync: false

